language: python
   
python:
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get install -y libspatialindex-dev libgeos-dev libgdal-dev gdal-bin python3-dev

install:
  - pip install -r dev-requirements.txt
  - python setup.py install
  - pip freeze

script:
  - python -m pytest tests
  
  
